### ISSUE TITLE
Failed to resolve import "../data/commodityDistributions.json" from "src\stores\store.ts". Does the file exist?

### ISSUE THREAD

**Issue by 25zs25** [Shan-yi-shuai/VAST-Challenge-MC2-2024#1]
您好，可以上传一下项目依赖的数据集文件夹吗，想运行看一下效果

**Comment by sduzs** [comment]
> 您好，可以上传一下项目依赖的数据集文件夹吗，想运行看一下效果

**Comment by Shan-yi-shuai** [comment]
居然有人看我写的代码。这个项目因为当时时间比较紧张写的比较混乱，好多数据都放在了前端，应该不止这一个文件需要上传。我后面把其中的一部分重构了一下放在了这个项目里面 https://github.com/Shan-yi-shuai/va-framework
你可以去看一下，这个是可以直接运行的，我把数据放在后端统一管理了。

**Comment by Shan-yi-shuai** [comment]
不好意思之前没有看到。这个项目因为当时时间比较紧张写的比较混乱，数据有些在前端有些在后端，应该不止这一个文件需要上传。我后面把其中的一部分重构了一下放在了这个项目里面&nbsp;https://github.com/Shan-yi-shuai/va-framework
你可以去看一下，这个是可以直接运行的，我把数据放在后端统一管理了。
&nbsp;


平常的万
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月7日(星期六) 晚上7:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [Shan-yi-shuai/VAST-Challenge-MC2-2024] Failed to resolve import &quot;../data/commodityDistributions.json&quot; from &quot;src\stores\store.ts&quot;. Does the file exist? (Issue #1)














 
Closed #1 as completed.

**Comment by 25zs25** [comment]
thanks for your reply.
best regrads.
